#! /bin/sh
# image - creates a disk image
# Distributed with nexware, licensed under the MIT license
# See LICENSE

disktypes="mbr end"
disktype=
# Get the disk type
for type in $disktypes
do
    # Check if they equal
    if [ $type = $1 ] && [ "$type" != "end" ]
    then
        disktype=$1
        break
    elif [ "$type" = "end" ]
    then
        echo "image: Invalid disk type"
        exit 1
    fi
done

# Be sure that output file and image size are set
if [ -z "$2" ] || [ -z "$3" ]
then
    echo "image: Parameter not set"
    exit 1
fi

# Get output file
output=$2
# Now create and format it
dd if=/dev/zero of=$output bs=1M count=$3
sleep 1
if [ "$disktype" = "mbr" ]
then
    # Partition it
    parted --script $output mklabel msdos mkpart p ext2 1M ${3}M set 1 boot on
fi
sleep 1
# Get loop device and setup the device
loopdev=$(losetup -Pf --show $output)
sleep 5
# Format data partition
mkfs.ext2 ${loopdev}p1
sleep 2

# Install Limine
mkdir fs
mount ${loopdev}p1 fs
mkdir fs/boot
# Install Limine
rm -rf limine
git clone https://github.com/limine-bootloader/limine.git --branch=v2.0-branch
cd limine
# Build limine
make
# Install stage 3
cp bin/limine.sys ../fs/limine.sys
cd ..
cp conf/limine.cfg $PWD/fs/boot/limine.cfg

umount fs
rm -r fs

# Delete partitions
losetup -d $loopdev

# Change ownership of file to caller
name=$(logname)
chown $name $output

# Install limine
./limine/bin/limine-install $output
sleep 1
